### PR TITLE
Fixes to be able to use TVM from an external project

### PR DESCRIPTION
**Pull request by BenjaminNavarro**
The main issues were:
 - The include folder was internally named tvm but installed under TVM
 - Header installation was incorrect. All files ended up in the same
   directory instead of following the directories hierarchy
 - The C++ standard was not exported

I chose to rename the include folder to TVM since it seems to be the convention in your other packages

### CODE REVIEW

**Comment by gergondet** [comment]
Hi @BenjaminNavarro 

Could you open the same PR but the other way around, i.e. fix the installation so that everything goes into `tvm` (and in the right sub-folders) and not change the internal name?

Thanks

**Comment by BenjaminNavarro** [comment]
Ok if prefer it like this

**Comment by arntanguy** [comment]
Oh sorry, I had the same patch laying around in my own branch, I should have opened a PR when I did it ;)

**Comment by gergondet** [comment]
Thanks, will merge when the CI passes

**Pull request merged**
